<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="FakesAssemblies\**" />
    <EmbeddedResource Remove="FakesAssemblies\**" />
    <None Remove="FakesAssemblies\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalDesignTimeBuildInput Remove="FakesAssemblies\**" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Management">
      <HintPath>..\..\..\..\Downloads\aa\AA Enabler\System.Management.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>